---

- name: determine if ZSH is installed
  command: which zsh
  register: check_zsh_installed
  ignore_errors: true
  changed_when: false
  tags: oh-my-zsh

- name: install or upgrade zsh
  apt: pkg=zsh,git state=latest
  when: not check_zsh_installed is success
  register: zsh_installed
  tags: zsh-install
