---
#Root or default user
- name: install or upgrade oh-my-zsh
  shell: curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  args:
    warn: false
  when:  zsh_installed is succeeded or not ohmyzsh_template_copied is success
  register: ohmyzsh_current_installed
  tags: oh-my-zsh

- name: load custom template
  template:
    src: zshrc.j2
    dest: $HOME/.zshrc
  register: ohmyzsh_template_copied
  when: ohmyzsh_current_installed is success
  tags: ohmyzsh_current_template

#Per existing user
- name : list users to apply oh-my-zsh
  shell: "getent passwd | awk -F: '$3 > 1000 {print $1}'"
  register: users

- name: Installing oh-my-zsh per user
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ item }}/.oh-my-zsh"
  with_items: users.stdout_lines
  register: ohmyzsh_installed
  tags: oh-my-zsh-installed
  ignore_errors: true

- name: Setting permissions per user
  file:
    path: "/home/{{ item }}/.oh-my-zsh"
    owner:  "{{ item }}"
    recurse: yes
  with_items: users.stdout_lines
  register: ohmyzsh_permissions
  when: ohmyzsh_installed is success
  tags: oh-my-zsh-permissions
  ignore_errors: true

- name: Setting default shell per user
  user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items: users.stdout_lines
  register: ohmyzsh_default
  when: ohmyzsh_permissions is success
  tags: oh-my-zsh-defaults
  ignore_errors: true

- name: load custom config zsh on existing users
  template:
    src: zshrc.j2
    dest: /home/{{ item }}/.zshrc
    owner: "{{ item }}"
    backup: yes
    mode: "0644"
  with_items: users.stdout_lines
  register: ohmyzsh_template_copied
  when: ohmyzsh_default is success
  tags: oh-my-zsh-config
  ignore_errors: true
  