---

- name: Installing oh-my-zsh per user
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "/home/{{ item.users }}/.oh-my-zsh"
  with_items:
      - { users: root }
      - { users: vagrant }
      - { users: ubuntu }
  register: ohmyzsh_installed
  tags: oh-my-zsh

- name: Setting permissions per user
  file:
    path: "/home/{{ item.users }}/.oh-my-zsh"
    owner:  "{{ item.users }}"
    recurse: yes
  with_items:
      - { users: root }
      - { users: vagrant }
      - { users: ubuntu }
  register: ohmyzsh_permissions
  when: ohmyzsh_installed is success
  tags: oh-my-zsh

- name: Setting default shell per user
  user:
    name: "{{ item.users }}"
    shell: /usr/bin/zsh
  with_items:
      - { users: vagrant }
      - { users: ubuntu }
  register: ohmyzsh_default
  when: ohmyzsh_permissions is success
  tags: oh-my-zsh

- name: load custom config zsh on existing users
  template:
    src: zshrc.j2
    dest: /home/{{ item.users }}/.zshrc
    owner: "{{ item.users }}"
    backup: yes
    mode: "0644"
  with_items:
      - { users: root }
      - { users: vagrant }
      - { users: ubuntu }
  register: ohmyzsh_template_copied
  when: ohmyzsh_default is success
  tags: oh-my-zsh